<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wheelchair_nav</name>
  <version>0.1.0</version>
  <description>Nav2による障害物回避付き人追従のための設定とlaunch</description>
  <maintainer email="ba2vwbus13wind@gmail.com">katsuya</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>dwb_core</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
